### ISSUE TITLE
Warning with H5Type

### ISSUE THREAD

**Issue by Pacatro** [metno/hdf5-rust#39]
I’ve been working with the crate and encountered a warning when using `#[derive(H5Type)]` in an enum:

```terminal
`H5Type` is not local
  move the `impl` block outside of this constant `_IMPL_H5TYPE_FOR_NNMode`
```

I’d like to understand why this happens and if there’s something I can do to resolve or work around it. Is this an expected behavior, or could it be related to the version I’m using?

Code:

```rust
#[derive(Debug, PartialEq, Eq, H5Type, Clone, Copy)]
#[repr(u8)]
pub enum NNMode {
    Train = 0,
    Test = 1,
}
```

Rust version: [`1.83.0`](https://blog.rust-lang.org/2024/11/28/Rust-1.83.0.html)

**Comment by magnusuMET** [comment]
This is fixed, but not released yet. It is a harmless warning, at least before edition 2024 is released. See more information about the lint here [RFC 3373](https://www.github.com/rust-lang/rfcs/pull/3373)

**Comment by jetuk** [comment]
The only issue for us is that it's causing clippy pipelines to fail on latest stable rust.

**Comment by jetuk** [comment]
I think a new `hdf5-metno-derive` release is needed to fix this issue.

**Comment by magnusuMET** [comment]
@jetuk Thanks for the heads up, forgot this fix belonged in that crate. I've tagged `hdf5-derive v0.9.2` which should be on crates.io now
